package com.huawei.cloud.dao;

import com.huawei.cloud.bean.AllPhone;
import com.huawei.cloud.bean.AllPhoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(AllPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(AllPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(AllPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(AllPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<AllPhone> selectByExample(AllPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    AllPhone selectByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") AllPhone record, @Param("example") AllPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") AllPhone record, @Param("example") AllPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(AllPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(AllPhone record);


	Integer countAllphone(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	List<AllPhone> selectAllphone(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void insertAllphone(@Param("alltelephone")String alltelephone,@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void deleteALLNum(@Param("middlename")Integer middlename,@Param("empno")Integer empno);
}