package com.huawei.cloud.dao;

import com.huawei.cloud.bean.AllPhone_2;
import com.huawei.cloud.bean.AllPhone_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllPhone_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(AllPhone_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(AllPhone_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(AllPhone_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(AllPhone_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<AllPhone_2> selectByExample(AllPhone_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    AllPhone_2 selectByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") AllPhone_2 record, @Param("example") AllPhone_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") AllPhone_2 record, @Param("example") AllPhone_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(AllPhone_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(AllPhone_2 record);
}