package com.huawei.cloud.dao;

import com.huawei.cloud.bean.AllPhone_1;
import com.huawei.cloud.bean.AllPhone_1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllPhone_1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(AllPhone_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(AllPhone_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(AllPhone_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(AllPhone_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<AllPhone_1> selectByExample(AllPhone_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    AllPhone_1 selectByPrimaryKey(Integer ttid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") AllPhone_1 record, @Param("example") AllPhone_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") AllPhone_1 record, @Param("example") AllPhone_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(AllPhone_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_allphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(AllPhone_1 record);
    
    

	Integer countAllphone_1(Integer middlename);

	List<AllPhone_1> selectAllphone_1(Integer middlename);

	void insertAllphone_1(@Param("alltelephone")String alltelephone,@Param("middlename")Integer middlename);

	void deleteALLNum_1(Integer middlename);
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}