package com.huawei.cloud.dao;

import com.huawei.cloud.bean.CardSend;
import com.huawei.cloud.bean.CardSendExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    long countByExample(CardSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int deleteByExample(CardSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int deleteByPrimaryKey(Integer kkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int insert(CardSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int insertSelective(CardSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    List<CardSend> selectByExample(CardSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    CardSend selectByPrimaryKey(Integer kkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") CardSend record, @Param("example") CardSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int updateByExample(@Param("record") CardSend record, @Param("example") CardSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int updateByPrimaryKeySelective(CardSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_card
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    int updateByPrimaryKey(CardSend record);

	Integer countCardRecord(@Param("middletag")Integer middletag,@Param("empno")Integer empno);
	
	List<CardSend> downCardSend(@Param("empno")Integer empno,@Param("middletag")Integer middletag);

	void deleteCard(@Param("middletag")Integer middletag,@Param("empno")Integer empno);
	
	void saveCardSend(@Param("comnum")String comnum,@Param("date")Date date,
	@Param("phonenum")String phonenum,@Param("carddetails")String carddetails,
	@Param("middletag")Integer middletag,@Param("empno")Integer empno);
}