package com.huawei.cloud.dao;

import com.huawei.cloud.bean.FailSend_1;
import com.huawei.cloud.bean.FailSend_1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FailSend_1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(FailSend_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(FailSend_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer ffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(FailSend_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(FailSend_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<FailSend_1> selectByExample(FailSend_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    FailSend_1 selectByPrimaryKey(Integer ffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") FailSend_1 record, @Param("example") FailSend_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") FailSend_1 record, @Param("example") FailSend_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(FailSend_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(FailSend_1 record);
    
    
    
    
    
    
    
    Integer countFailSend_1(Integer middlename);

	List<FailSend_1> selectFailSend_1(Integer middlename);

	void addFailsend_1(@Param("sendfail")String sendfail,@Param("middlename") Integer middlename);

	void deleteFaildSend_1(Integer middlename);

    
    
    
    
    
    
    
    
    
}