package com.huawei.cloud.dao;

import com.huawei.cloud.bean.FailSend_2;
import com.huawei.cloud.bean.FailSend_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FailSend_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(FailSend_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(FailSend_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(FailSend_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(FailSend_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<FailSend_2> selectByExample(FailSend_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    FailSend_2 selectByPrimaryKey(Integer ffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") FailSend_2 record, @Param("example") FailSend_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") FailSend_2 record, @Param("example") FailSend_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(FailSend_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_failsendphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(FailSend_2 record);
}