package com.huawei.cloud.dao;

import com.huawei.cloud.bean.GetFail_2;
import com.huawei.cloud.bean.GetFail_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GetFail_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(GetFail_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(GetFail_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(GetFail_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(GetFail_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<GetFail_2> selectByExample(GetFail_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    GetFail_2 selectByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") GetFail_2 record, @Param("example") GetFail_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") GetFail_2 record, @Param("example") GetFail_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(GetFail_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(GetFail_2 record);
}