package com.huawei.cloud.dao;

import com.huawei.cloud.bean.GetFail_1;
import com.huawei.cloud.bean.GetFail_1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GetFail_1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(GetFail_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(GetFail_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(GetFail_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(GetFail_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<GetFail_1> selectByExample(GetFail_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    GetFail_1 selectByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") GetFail_1 record, @Param("example") GetFail_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") GetFail_1 record, @Param("example") GetFail_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(GetFail_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(GetFail_1 record);
    
    
   
    
	Integer countGetfailphones_1(Integer middlename);

	List<GetFail_1> selectGetfailphone_1(Integer middlename);

	void addGetfail_1(@Param("getfailsendphone")String getfailsendphone,@Param("middlename")Integer middlename );

	void deleteGetFailLogin_1(Integer middlename);
    
    
    
    
    
    
    
}