package com.huawei.cloud.dao;

import com.huawei.cloud.bean.GetFail;
import com.huawei.cloud.bean.GetFailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GetFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(GetFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(GetFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(GetFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(GetFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<GetFail> selectByExample(GetFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    GetFail selectByPrimaryKey(Integer gfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") GetFail record, @Param("example") GetFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") GetFail record, @Param("example") GetFailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(GetFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_getfailphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(GetFail record);

	Integer countGetfailphones(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	List<GetFail> selectGetfailphone(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void addGetfail(@Param("getfailsendphone")String getfailsendphone,@Param("middlename")Integer middlename ,@Param("empno")Integer empno);

	void deleteGetFailLogin(@Param("middlename")Integer middlename,@Param("empno")Integer empno);
}