package com.huawei.cloud.dao;

import com.huawei.cloud.bean.HistorySame;
import com.huawei.cloud.bean.HistorySameExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistorySameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    long countByExample(HistorySameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int deleteByExample(HistorySameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int deleteByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int insert(HistorySame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int insertSelective(HistorySame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    List<HistorySame> selectByExample(HistorySameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    HistorySame selectByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") HistorySame record, @Param("example") HistorySameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int updateByExample(@Param("record") HistorySame record, @Param("example") HistorySameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int updateByPrimaryKeySelective(HistorySame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    int updateByPrimaryKey(HistorySame record);

	void saveHistory(@Param("successgetphone")String successphone,@Param("adddate") Date adddate);
	
	void delHistory();
	
	Integer countHistory();
	
	List<HistorySame> searchSameHistory(@Param("successgetphone") String successgetphone);
	
	
	
	
	
	
	
	
	
	
}