package com.huawei.cloud.dao;

import com.huawei.cloud.bean.Pending_2;
import com.huawei.cloud.bean.Pending_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Pending_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(Pending_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(Pending_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(Pending_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(Pending_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<Pending_2> selectByExample(Pending_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    Pending_2 selectByPrimaryKey(Integer ppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pending_2 record, @Param("example") Pending_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") Pending_2 record, @Param("example") Pending_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(Pending_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_pending_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(Pending_2 record);
}