package com.huawei.cloud.dao;

import com.huawei.cloud.bean.Status;
import com.huawei.cloud.bean.StatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    long countByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int deleteByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int insert(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int insertSelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    List<Status> selectByExample(StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    Status selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int updateByExample(@Param("record") Status record, @Param("example") StatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int updateByPrimaryKeySelective(Status record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_status
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    int updateByPrimaryKey( Status record);
}