package com.huawei.cloud.dao;

import com.huawei.cloud.bean.SuccessGet_1;
import com.huawei.cloud.bean.SuccessGet_1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessGet_1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(SuccessGet_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(SuccessGet_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(SuccessGet_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(SuccessGet_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<SuccessGet_1> selectByExample(SuccessGet_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    SuccessGet_1 selectByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuccessGet_1 record, @Param("example") SuccessGet_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") SuccessGet_1 record, @Param("example") SuccessGet_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessGet_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone_1
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(SuccessGet_1 record);
    
	Integer countSuccessGet_1(Integer middlename);

	List<SuccessGet_1> selectSuccessGet_1(Integer middlename);

	void addSuccessGet_1(@Param("successgetphone")String successgetphone, @Param("middlename")Integer middlename);

	void deleteSuccGet_1(Integer middlename);
	
	
    
    
    
    
    
    
    
    
    
    
}