package com.huawei.cloud.dao;

import com.huawei.cloud.bean.SuccessGet;
import com.huawei.cloud.bean.SuccessGetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessGetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(SuccessGetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(SuccessGetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(SuccessGet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(SuccessGet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<SuccessGet> selectByExample(SuccessGetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    SuccessGet selectByPrimaryKey(Integer sgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuccessGet record, @Param("example") SuccessGetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") SuccessGet record, @Param("example") SuccessGetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessGet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(SuccessGet record);
    
    
    
    
    
    

	Integer countSuccessGet(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	List<SuccessGet> selectSuccessGet(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void addSuccessGet(@Param("successgetphone")String successgetphone, @Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void deleteSuccGet(@Param("middlename")Integer middlename,@Param("empno")Integer empno);
	
	
	
	
	
	
	
	
}