package com.huawei.cloud.dao;

import com.huawei.cloud.bean.Succreturn_1;
import com.huawei.cloud.bean.Succreturn_1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Succreturn_1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(Succreturn_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(Succreturn_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(Succreturn_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(Succreturn_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<Succreturn_1> selectByExample(Succreturn_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    Succreturn_1 selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Succreturn_1 record, @Param("example") Succreturn_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") Succreturn_1 record, @Param("example") Succreturn_1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(Succreturn_1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_1
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(Succreturn_1 record);

	Integer countSuccReturn_1(Integer middlename);

	void addSuccReturn_1(@Param("succreturn")String succreturn,@Param("middlename") Integer middlename);

	List<Succreturn_1> selectSuccreturn_1(Integer middlename);

	void deleteSuccreturn_1(Integer middlename);
	
	
	
	
	
	
	
	
}