package com.huawei.cloud.dao;

import com.huawei.cloud.bean.Succreturn_2;
import com.huawei.cloud.bean.Succreturn_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Succreturn_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(Succreturn_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(Succreturn_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(Succreturn_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(Succreturn_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<Succreturn_2> selectByExample(Succreturn_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    Succreturn_2 selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Succreturn_2 record, @Param("example") Succreturn_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") Succreturn_2 record, @Param("example") Succreturn_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(Succreturn_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succreturn_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(Succreturn_2 record);
}