package com.huawei.cloud.dao;

import com.huawei.cloud.bean.SuccessLogin;
import com.huawei.cloud.bean.SuccessLoginExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    long countByExample(SuccessLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByExample(SuccessLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insert(SuccessLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int insertSelective(SuccessLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    List<SuccessLogin> selectByExample(SuccessLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    SuccessLogin selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuccessLogin record, @Param("example") SuccessLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByExample(@Param("record") SuccessLogin record, @Param("example") SuccessLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    int updateByPrimaryKey(SuccessLogin record);

  
	Integer countSuccessLogin(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	List<SuccessLogin> selectSuccessLogin(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	void addSuccessLogin(@Param("successphone") String successphone,@Param("middlename") Integer middlename,@Param("empno")Integer empno,@Param("date")Date date);

	void deleteSuccLogin(@Param("middlename")Integer middlename,@Param("empno")Integer empno);

	String seleLogin(String phonenum);

}