package com.huawei.cloud.dao;

import com.huawei.cloud.bean.SuccessLogin_2;
import com.huawei.cloud.bean.SuccessLogin_2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuccessLogin_2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    long countByExample(SuccessLogin_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByExample(SuccessLogin_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int deleteByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insert(SuccessLogin_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int insertSelective(SuccessLogin_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    List<SuccessLogin_2> selectByExample(SuccessLogin_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    SuccessLogin_2 selectByPrimaryKey(Integer ssid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuccessLogin_2 record, @Param("example") SuccessLogin_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByExample(@Param("record") SuccessLogin_2 record, @Param("example") SuccessLogin_2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKeySelective(SuccessLogin_2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_succloginphone_2
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    int updateByPrimaryKey(SuccessLogin_2 record);
}