package com.huawei.cloud.dao;

import com.huawei.cloud.bean.Txtupload;
import com.huawei.cloud.bean.TxtuploadExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxtuploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    long countByExample(TxtuploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int deleteByExample(TxtuploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int deleteByPrimaryKey(Integer txtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int insert(Txtupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int insertSelective(Txtupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    List<Txtupload> selectByExample(TxtuploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    Txtupload selectByPrimaryKey(Integer txtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") Txtupload record, @Param("example") TxtuploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int updateByExample(@Param("record") Txtupload record, @Param("example") TxtuploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int updateByPrimaryKeySelective(Txtupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    int updateByPrimaryKey(Txtupload record);

	void inserttxtupload(@Param("empno")Integer empno, @Param("date")Date date,@Param("latefilename") String latefilename,@Param("tarUrl") String tarUrl);

	List<Txtupload> selectTxtByempno(@Param("empno")Integer empno);

	void deleteByTxtname(String txtname);

	




}