package com.huawei.cloud.bean;

public class AllPhone_1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_allphone_1.ttid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer ttid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_allphone_1.alltelephone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private String alltelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_allphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_allphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_allphone_1.ttid
     *
     * @return the value of tab_allphone_1.ttid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getTtid() {
        return ttid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_allphone_1.ttid
     *
     * @param ttid the value for tab_allphone_1.ttid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setTtid(Integer ttid) {
        this.ttid = ttid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_allphone_1.alltelephone
     *
     * @return the value of tab_allphone_1.alltelephone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public String getAlltelephone() {
        return alltelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_allphone_1.alltelephone
     *
     * @param alltelephone the value for tab_allphone_1.alltelephone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setAlltelephone(String alltelephone) {
        this.alltelephone = alltelephone == null ? null : alltelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_allphone_1.empno
     *
     * @return the value of tab_allphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_allphone_1.empno
     *
     * @param empno the value for tab_allphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_allphone_1.middletag
     *
     * @return the value of tab_allphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_allphone_1.middletag
     *
     * @param middletag the value for tab_allphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}