package com.huawei.cloud.bean;

import java.util.Date;

public class CardSend {
    @Override
	public String toString() {
		return "CardSend [kkid=" + kkid + ", comnum=" + comnum + ", date=" + date + ", phonenum=" + phonenum
				+ ", carddetails=" + carddetails + ", empno=" + empno + ", middletag=" + middletag + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.kkid
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private Integer kkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.comnum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private String comnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.date
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.phonenum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.carddetails
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private String carddetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.empno
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_card.middletag
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.kkid
     *
     * @return the value of tab_card.kkid
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public Integer getKkid() {
        return kkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.kkid
     *
     * @param kkid the value for tab_card.kkid
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setKkid(Integer kkid) {
        this.kkid = kkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.comnum
     *
     * @return the value of tab_card.comnum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public String getComnum() {
        return comnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.comnum
     *
     * @param comnum the value for tab_card.comnum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setComnum(String comnum) {
        this.comnum = comnum == null ? null : comnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.date
     *
     * @return the value of tab_card.date
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.date
     *
     * @param date the value for tab_card.date
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.phonenum
     *
     * @return the value of tab_card.phonenum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.phonenum
     *
     * @param phonenum the value for tab_card.phonenum
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.carddetails
     *
     * @return the value of tab_card.carddetails
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public String getCarddetails() {
        return carddetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.carddetails
     *
     * @param carddetails the value for tab_card.carddetails
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setCarddetails(String carddetails) {
        this.carddetails = carddetails == null ? null : carddetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.empno
     *
     * @return the value of tab_card.empno
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.empno
     *
     * @param empno the value for tab_card.empno
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_card.middletag
     *
     * @return the value of tab_card.middletag
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_card.middletag
     *
     * @param middletag the value for tab_card.middletag
     *
     * @mbg.generated Wed Jun 19 09:21:35 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}