package com.huawei.cloud.bean;

public class FailSend_2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_failsendphone_2.ffid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer ffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_failsendphone_2.sendfail
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private String sendfail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_failsendphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_failsendphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_failsendphone_2.ffid
     *
     * @return the value of tab_failsendphone_2.ffid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getFfid() {
        return ffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_failsendphone_2.ffid
     *
     * @param ffid the value for tab_failsendphone_2.ffid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setFfid(Integer ffid) {
        this.ffid = ffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_failsendphone_2.sendfail
     *
     * @return the value of tab_failsendphone_2.sendfail
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public String getSendfail() {
        return sendfail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_failsendphone_2.sendfail
     *
     * @param sendfail the value for tab_failsendphone_2.sendfail
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setSendfail(String sendfail) {
        this.sendfail = sendfail == null ? null : sendfail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_failsendphone_2.empno
     *
     * @return the value of tab_failsendphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_failsendphone_2.empno
     *
     * @param empno the value for tab_failsendphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_failsendphone_2.middletag
     *
     * @return the value of tab_failsendphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_failsendphone_2.middletag
     *
     * @param middletag the value for tab_failsendphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}