package com.huawei.cloud.bean;

public class GetFail_1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_getfailphone_1.gfid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer gfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_getfailphone_1.getfailloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private String getfailloginphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_getfailphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_getfailphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_getfailphone_1.gfid
     *
     * @return the value of tab_getfailphone_1.gfid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getGfid() {
        return gfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_getfailphone_1.gfid
     *
     * @param gfid the value for tab_getfailphone_1.gfid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setGfid(Integer gfid) {
        this.gfid = gfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_getfailphone_1.getfailloginphone
     *
     * @return the value of tab_getfailphone_1.getfailloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public String getGetfailloginphone() {
        return getfailloginphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_getfailphone_1.getfailloginphone
     *
     * @param getfailloginphone the value for tab_getfailphone_1.getfailloginphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setGetfailloginphone(String getfailloginphone) {
        this.getfailloginphone = getfailloginphone == null ? null : getfailloginphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_getfailphone_1.empno
     *
     * @return the value of tab_getfailphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_getfailphone_1.empno
     *
     * @param empno the value for tab_getfailphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_getfailphone_1.middletag
     *
     * @return the value of tab_getfailphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_getfailphone_1.middletag
     *
     * @param middletag the value for tab_getfailphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}