package com.huawei.cloud.bean;

import java.util.Date;

public class HistorySame {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_history.sgid
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    private Integer sgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_history.successgetphone
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    private String successgetphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_history.adddate
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    private Date adddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_history.sgid
     *
     * @return the value of tab_history.sgid
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public Integer getSgid() {
        return sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_history.sgid
     *
     * @param sgid the value for tab_history.sgid
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void setSgid(Integer sgid) {
        this.sgid = sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_history.successgetphone
     *
     * @return the value of tab_history.successgetphone
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public String getSuccessgetphone() {
        return successgetphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_history.successgetphone
     *
     * @param successgetphone the value for tab_history.successgetphone
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void setSuccessgetphone(String successgetphone) {
        this.successgetphone = successgetphone == null ? null : successgetphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_history.adddate
     *
     * @return the value of tab_history.adddate
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_history.adddate
     *
     * @param adddate the value for tab_history.adddate
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }
}