package com.huawei.cloud.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HistorySameExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public HistorySameExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSgidIsNull() {
            addCriterion("sgid is null");
            return (Criteria) this;
        }

        public Criteria andSgidIsNotNull() {
            addCriterion("sgid is not null");
            return (Criteria) this;
        }

        public Criteria andSgidEqualTo(Integer value) {
            addCriterion("sgid =", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidNotEqualTo(Integer value) {
            addCriterion("sgid <>", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidGreaterThan(Integer value) {
            addCriterion("sgid >", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sgid >=", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidLessThan(Integer value) {
            addCriterion("sgid <", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidLessThanOrEqualTo(Integer value) {
            addCriterion("sgid <=", value, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidIn(List<Integer> values) {
            addCriterion("sgid in", values, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidNotIn(List<Integer> values) {
            addCriterion("sgid not in", values, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidBetween(Integer value1, Integer value2) {
            addCriterion("sgid between", value1, value2, "sgid");
            return (Criteria) this;
        }

        public Criteria andSgidNotBetween(Integer value1, Integer value2) {
            addCriterion("sgid not between", value1, value2, "sgid");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneIsNull() {
            addCriterion("successgetphone is null");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneIsNotNull() {
            addCriterion("successgetphone is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneEqualTo(String value) {
            addCriterion("successgetphone =", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneNotEqualTo(String value) {
            addCriterion("successgetphone <>", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneGreaterThan(String value) {
            addCriterion("successgetphone >", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneGreaterThanOrEqualTo(String value) {
            addCriterion("successgetphone >=", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneLessThan(String value) {
            addCriterion("successgetphone <", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneLessThanOrEqualTo(String value) {
            addCriterion("successgetphone <=", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneLike(String value) {
            addCriterion("successgetphone like", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneNotLike(String value) {
            addCriterion("successgetphone not like", value, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneIn(List<String> values) {
            addCriterion("successgetphone in", values, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneNotIn(List<String> values) {
            addCriterion("successgetphone not in", values, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneBetween(String value1, String value2) {
            addCriterion("successgetphone between", value1, value2, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andSuccessgetphoneNotBetween(String value1, String value2) {
            addCriterion("successgetphone not between", value1, value2, "successgetphone");
            return (Criteria) this;
        }

        public Criteria andAdddateIsNull() {
            addCriterion("adddate is null");
            return (Criteria) this;
        }

        public Criteria andAdddateIsNotNull() {
            addCriterion("adddate is not null");
            return (Criteria) this;
        }

        public Criteria andAdddateEqualTo(Date value) {
            addCriterionForJDBCDate("adddate =", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("adddate <>", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateGreaterThan(Date value) {
            addCriterionForJDBCDate("adddate >", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("adddate >=", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateLessThan(Date value) {
            addCriterionForJDBCDate("adddate <", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("adddate <=", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateIn(List<Date> values) {
            addCriterionForJDBCDate("adddate in", values, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("adddate not in", values, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("adddate between", value1, value2, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("adddate not between", value1, value2, "adddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_history
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 01 11:40:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_history
     *
     * @mbg.generated Mon Jul 01 11:40:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}