package com.huawei.cloud.bean;


public class PhoneNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_phone.pid
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_phone.telephone
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_phone.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer status_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_phone.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer empno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_phone.pid
     *
     * @return the value of tab_phone.pid
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_phone.pid
     *
     * @param pid the value for tab_phone.pid
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_phone.telephone
     *
     * @return the value of tab_phone.telephone
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_phone.telephone
     *
     * @param telephone the value for tab_phone.telephone
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_phone.status_id
     *
     * @return the value of tab_phone.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getStatus_id() {
        return status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_phone.status_id
     *
     * @param status_id the value for tab_phone.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setStatus_id(Integer status_id) {
        this.status_id = status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_phone.empno
     *
     * @return the value of tab_phone.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_phone.empno
     *
     * @param empno the value for tab_phone.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

	public PhoneNum(Integer pid, String telephone, Integer status_id, Integer empno) {
		super();
		this.pid = pid;
		this.telephone = telephone;
		this.status_id = status_id;
		this.empno = empno;
	}

	public PhoneNum() {
		super();
	}

	@Override
	public String toString() {
		return "PhoneNum [pid=" + pid + ", telephone=" + telephone + ", status_id=" + status_id + ", empno=" + empno + "]";
	}
    
    
    
    
}