package com.huawei.cloud.bean;

import java.util.Date;

public class Repetition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.rid
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.repetition
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private String repetition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.adddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private Date adddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.empno
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.olddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private Date olddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_repetition.middletag
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.rid
     *
     * @return the value of tab_repetition.rid
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.rid
     *
     * @param rid the value for tab_repetition.rid
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.repetition
     *
     * @return the value of tab_repetition.repetition
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public String getRepetition() {
        return repetition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.repetition
     *
     * @param repetition the value for tab_repetition.repetition
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setRepetition(String repetition) {
        this.repetition = repetition == null ? null : repetition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.adddate
     *
     * @return the value of tab_repetition.adddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.adddate
     *
     * @param adddate the value for tab_repetition.adddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.empno
     *
     * @return the value of tab_repetition.empno
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.empno
     *
     * @param empno the value for tab_repetition.empno
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.olddate
     *
     * @return the value of tab_repetition.olddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public Date getOlddate() {
        return olddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.olddate
     *
     * @param olddate the value for tab_repetition.olddate
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setOlddate(Date olddate) {
        this.olddate = olddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_repetition.middletag
     *
     * @return the value of tab_repetition.middletag
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_repetition.middletag
     *
     * @param middletag the value for tab_repetition.middletag
     *
     * @mbg.generated Fri Jul 05 17:12:11 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}