package com.huawei.cloud.bean;

public class Status {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_status.s_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_status.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_status.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_status.s_id
     *
     * @return the value of tab_status.s_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_status.s_id
     *
     * @param sId the value for tab_status.s_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_status.empno
     *
     * @return the value of tab_status.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_status.empno
     *
     * @param empno the value for tab_status.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_status.status_id
     *
     * @return the value of tab_status.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_status.status_id
     *
     * @param statusId the value for tab_status.status_id
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

	public Status(Integer sId, Integer empno, Integer statusId) {
		super();
		this.sId = sId;
		this.empno = empno;
		this.statusId = statusId;
	}

	public Status() {
		super();
	}

	@Override
	public String toString() {
		return "Status [sId=" + sId + ", empno=" + empno + ", statusId=" + statusId + "]";
	}
    
    
    
    
    
    
}