package com.huawei.cloud.bean;

public class SuccessGet_1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_1.sgid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer sgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_1.successgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private String successgetphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_1.sgid
     *
     * @return the value of tab_succgetphone_1.sgid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getSgid() {
        return sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_1.sgid
     *
     * @param sgid the value for tab_succgetphone_1.sgid
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setSgid(Integer sgid) {
        this.sgid = sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_1.successgetphone
     *
     * @return the value of tab_succgetphone_1.successgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public String getSuccessgetphone() {
        return successgetphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_1.successgetphone
     *
     * @param successgetphone the value for tab_succgetphone_1.successgetphone
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setSuccessgetphone(String successgetphone) {
        this.successgetphone = successgetphone == null ? null : successgetphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_1.empno
     *
     * @return the value of tab_succgetphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_1.empno
     *
     * @param empno the value for tab_succgetphone_1.empno
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_1.middletag
     *
     * @return the value of tab_succgetphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_1.middletag
     *
     * @param middletag the value for tab_succgetphone_1.middletag
     *
     * @mbg.generated Thu May 30 11:35:03 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}