package com.huawei.cloud.bean;

public class SuccessLogin_2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succloginphone_2.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succloginphone_2.succussphone
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private String succussphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succloginphone_2.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succloginphone_2.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succloginphone_2.ssid
     *
     * @return the value of tab_succloginphone_2.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succloginphone_2.ssid
     *
     * @param ssid the value for tab_succloginphone_2.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succloginphone_2.succussphone
     *
     * @return the value of tab_succloginphone_2.succussphone
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public String getSuccussphone() {
        return succussphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succloginphone_2.succussphone
     *
     * @param succussphone the value for tab_succloginphone_2.succussphone
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setSuccussphone(String succussphone) {
        this.succussphone = succussphone == null ? null : succussphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succloginphone_2.empno
     *
     * @return the value of tab_succloginphone_2.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succloginphone_2.empno
     *
     * @param empno the value for tab_succloginphone_2.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succloginphone_2.middletag
     *
     * @return the value of tab_succloginphone_2.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succloginphone_2.middletag
     *
     * @param middletag the value for tab_succloginphone_2.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}