package com.huawei.cloud.bean;

import java.util.Date;

public class Succreturn_1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succreturn_1.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer ssid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succreturn_1.succesreturn
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private String succesreturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succreturn_1.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer middletag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succreturn_1.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succreturn_1.adddate
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    private Date adddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succreturn_1.ssid
     *
     * @return the value of tab_succreturn_1.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succreturn_1.ssid
     *
     * @param ssid the value for tab_succreturn_1.ssid
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setSsid(Integer ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succreturn_1.succesreturn
     *
     * @return the value of tab_succreturn_1.succesreturn
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public String getSuccesreturn() {
        return succesreturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succreturn_1.succesreturn
     *
     * @param succesreturn the value for tab_succreturn_1.succesreturn
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setSuccesreturn(String succesreturn) {
        this.succesreturn = succesreturn == null ? null : succesreturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succreturn_1.middletag
     *
     * @return the value of tab_succreturn_1.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succreturn_1.middletag
     *
     * @param middletag the value for tab_succreturn_1.middletag
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succreturn_1.empno
     *
     * @return the value of tab_succreturn_1.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succreturn_1.empno
     *
     * @param empno the value for tab_succreturn_1.empno
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succreturn_1.adddate
     *
     * @return the value of tab_succreturn_1.adddate
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succreturn_1.adddate
     *
     * @param adddate the value for tab_succreturn_1.adddate
     *
     * @mbg.generated Sat Jun 22 09:46:12 CST 2019
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }
}