package com.huawei.cloud.bean;

public class SuccessGet_2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_2.sgid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer sgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_2.successgetphone
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private String successgetphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_succgetphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    private Integer middletag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_2.sgid
     *
     * @return the value of tab_succgetphone_2.sgid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getSgid() {
        return sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_2.sgid
     *
     * @param sgid the value for tab_succgetphone_2.sgid
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setSgid(Integer sgid) {
        this.sgid = sgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_2.successgetphone
     *
     * @return the value of tab_succgetphone_2.successgetphone
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public String getSuccessgetphone() {
        return successgetphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_2.successgetphone
     *
     * @param successgetphone the value for tab_succgetphone_2.successgetphone
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setSuccessgetphone(String successgetphone) {
        this.successgetphone = successgetphone == null ? null : successgetphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_2.empno
     *
     * @return the value of tab_succgetphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_2.empno
     *
     * @param empno the value for tab_succgetphone_2.empno
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_succgetphone_2.middletag
     *
     * @return the value of tab_succgetphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public Integer getMiddletag() {
        return middletag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_succgetphone_2.middletag
     *
     * @param middletag the value for tab_succgetphone_2.middletag
     *
     * @mbg.generated Sun Jun 16 10:11:06 CST 2019
     */
    public void setMiddletag(Integer middletag) {
        this.middletag = middletag;
    }
}