package com.huawei.cloud.bean;

public class TxtFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_middname.mid
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_middname.empno
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_middname.tabname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    private String tabname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_middname.clientname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    private String clientname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_middname.mid
     *
     * @return the value of tab_middname.mid
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_middname.mid
     *
     * @param mid the value for tab_middname.mid
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_middname.empno
     *
     * @return the value of tab_middname.empno
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_middname.empno
     *
     * @param empno the value for tab_middname.empno
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_middname.tabname
     *
     * @return the value of tab_middname.tabname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public String getTabname() {
        return tabname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_middname.tabname
     *
     * @param tabname the value for tab_middname.tabname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public void setTabname(String tabname) {
        this.tabname = tabname == null ? null : tabname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_middname.clientname
     *
     * @return the value of tab_middname.clientname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_middname.clientname
     *
     * @param clientname the value for tab_middname.clientname
     *
     * @mbg.generated Wed May 29 19:52:44 CST 2019
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }
}