package com.huawei.cloud.bean;

import java.util.Date;

public class Txtupload {
    @Override
	public String toString() {
		return "Txtupload [txtid=" + txtid + ", txtname=" + txtname + ", adddate=" + adddate + ", txturl=" + txturl
				+ ", empno=" + empno + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_uptxt.txtid
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    private Integer txtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_uptxt.txtname
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    private String txtname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_uptxt.adddate
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    private Date adddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_uptxt.txturl
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    private String txturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_uptxt.empno
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    private Integer empno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_uptxt.txtid
     *
     * @return the value of tab_uptxt.txtid
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public Integer getTxtid() {
        return txtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_uptxt.txtid
     *
     * @param txtid the value for tab_uptxt.txtid
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setTxtid(Integer txtid) {
        this.txtid = txtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_uptxt.txtname
     *
     * @return the value of tab_uptxt.txtname
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public String getTxtname() {
        return txtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_uptxt.txtname
     *
     * @param txtname the value for tab_uptxt.txtname
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setTxtname(String txtname) {
        this.txtname = txtname == null ? null : txtname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_uptxt.adddate
     *
     * @return the value of tab_uptxt.adddate
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_uptxt.adddate
     *
     * @param adddate the value for tab_uptxt.adddate
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_uptxt.txturl
     *
     * @return the value of tab_uptxt.txturl
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public String getTxturl() {
        return txturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_uptxt.txturl
     *
     * @param txturl the value for tab_uptxt.txturl
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setTxturl(String txturl) {
        this.txturl = txturl == null ? null : txturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_uptxt.empno
     *
     * @return the value of tab_uptxt.empno
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_uptxt.empno
     *
     * @param empno the value for tab_uptxt.empno
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }
}