package com.huawei.cloud.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TxtuploadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public TxtuploadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTxtidIsNull() {
            addCriterion("txtid is null");
            return (Criteria) this;
        }

        public Criteria andTxtidIsNotNull() {
            addCriterion("txtid is not null");
            return (Criteria) this;
        }

        public Criteria andTxtidEqualTo(Integer value) {
            addCriterion("txtid =", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidNotEqualTo(Integer value) {
            addCriterion("txtid <>", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidGreaterThan(Integer value) {
            addCriterion("txtid >", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("txtid >=", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidLessThan(Integer value) {
            addCriterion("txtid <", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidLessThanOrEqualTo(Integer value) {
            addCriterion("txtid <=", value, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidIn(List<Integer> values) {
            addCriterion("txtid in", values, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidNotIn(List<Integer> values) {
            addCriterion("txtid not in", values, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidBetween(Integer value1, Integer value2) {
            addCriterion("txtid between", value1, value2, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtidNotBetween(Integer value1, Integer value2) {
            addCriterion("txtid not between", value1, value2, "txtid");
            return (Criteria) this;
        }

        public Criteria andTxtnameIsNull() {
            addCriterion("txtname is null");
            return (Criteria) this;
        }

        public Criteria andTxtnameIsNotNull() {
            addCriterion("txtname is not null");
            return (Criteria) this;
        }

        public Criteria andTxtnameEqualTo(String value) {
            addCriterion("txtname =", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameNotEqualTo(String value) {
            addCriterion("txtname <>", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameGreaterThan(String value) {
            addCriterion("txtname >", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameGreaterThanOrEqualTo(String value) {
            addCriterion("txtname >=", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameLessThan(String value) {
            addCriterion("txtname <", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameLessThanOrEqualTo(String value) {
            addCriterion("txtname <=", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameLike(String value) {
            addCriterion("txtname like", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameNotLike(String value) {
            addCriterion("txtname not like", value, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameIn(List<String> values) {
            addCriterion("txtname in", values, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameNotIn(List<String> values) {
            addCriterion("txtname not in", values, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameBetween(String value1, String value2) {
            addCriterion("txtname between", value1, value2, "txtname");
            return (Criteria) this;
        }

        public Criteria andTxtnameNotBetween(String value1, String value2) {
            addCriterion("txtname not between", value1, value2, "txtname");
            return (Criteria) this;
        }

        public Criteria andAdddateIsNull() {
            addCriterion("adddate is null");
            return (Criteria) this;
        }

        public Criteria andAdddateIsNotNull() {
            addCriterion("adddate is not null");
            return (Criteria) this;
        }

        public Criteria andAdddateEqualTo(Date value) {
            addCriterion("adddate =", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotEqualTo(Date value) {
            addCriterion("adddate <>", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateGreaterThan(Date value) {
            addCriterion("adddate >", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateGreaterThanOrEqualTo(Date value) {
            addCriterion("adddate >=", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateLessThan(Date value) {
            addCriterion("adddate <", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateLessThanOrEqualTo(Date value) {
            addCriterion("adddate <=", value, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateIn(List<Date> values) {
            addCriterion("adddate in", values, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotIn(List<Date> values) {
            addCriterion("adddate not in", values, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateBetween(Date value1, Date value2) {
            addCriterion("adddate between", value1, value2, "adddate");
            return (Criteria) this;
        }

        public Criteria andAdddateNotBetween(Date value1, Date value2) {
            addCriterion("adddate not between", value1, value2, "adddate");
            return (Criteria) this;
        }

        public Criteria andTxturlIsNull() {
            addCriterion("txturl is null");
            return (Criteria) this;
        }

        public Criteria andTxturlIsNotNull() {
            addCriterion("txturl is not null");
            return (Criteria) this;
        }

        public Criteria andTxturlEqualTo(String value) {
            addCriterion("txturl =", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlNotEqualTo(String value) {
            addCriterion("txturl <>", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlGreaterThan(String value) {
            addCriterion("txturl >", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlGreaterThanOrEqualTo(String value) {
            addCriterion("txturl >=", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlLessThan(String value) {
            addCriterion("txturl <", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlLessThanOrEqualTo(String value) {
            addCriterion("txturl <=", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlLike(String value) {
            addCriterion("txturl like", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlNotLike(String value) {
            addCriterion("txturl not like", value, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlIn(List<String> values) {
            addCriterion("txturl in", values, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlNotIn(List<String> values) {
            addCriterion("txturl not in", values, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlBetween(String value1, String value2) {
            addCriterion("txturl between", value1, value2, "txturl");
            return (Criteria) this;
        }

        public Criteria andTxturlNotBetween(String value1, String value2) {
            addCriterion("txturl not between", value1, value2, "txturl");
            return (Criteria) this;
        }

        public Criteria andEmpnoIsNull() {
            addCriterion("empno is null");
            return (Criteria) this;
        }

        public Criteria andEmpnoIsNotNull() {
            addCriterion("empno is not null");
            return (Criteria) this;
        }

        public Criteria andEmpnoEqualTo(Integer value) {
            addCriterion("empno =", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoNotEqualTo(Integer value) {
            addCriterion("empno <>", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoGreaterThan(Integer value) {
            addCriterion("empno >", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("empno >=", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoLessThan(Integer value) {
            addCriterion("empno <", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoLessThanOrEqualTo(Integer value) {
            addCriterion("empno <=", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoIn(List<Integer> values) {
            addCriterion("empno in", values, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoNotIn(List<Integer> values) {
            addCriterion("empno not in", values, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoBetween(Integer value1, Integer value2) {
            addCriterion("empno between", value1, value2, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoNotBetween(Integer value1, Integer value2) {
            addCriterion("empno not between", value1, value2, "empno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_uptxt
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 01 13:32:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_uptxt
     *
     * @mbg.generated Sat Jun 01 13:32:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}