package com.huawei.cloud.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.ename
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.gender
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.role
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.password
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.empno
     *
     * @return the value of tab_emp.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.empno
     *
     * @param empno the value for tab_emp.empno
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.ename
     *
     * @return the value of tab_emp.ename
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.ename
     *
     * @param ename the value for tab_emp.ename
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.gender
     *
     * @return the value of tab_emp.gender
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.gender
     *
     * @param gender the value for tab_emp.gender
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.role
     *
     * @return the value of tab_emp.role
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.role
     *
     * @param role the value for tab_emp.role
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.password
     *
     * @return the value of tab_emp.password
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.password
     *
     * @param password the value for tab_emp.password
     *
     * @mbg.generated Fri Apr 26 13:25:41 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

	public User(Integer empno, String ename, Integer gender, Integer role, String password) {
		super();
		this.empno = empno;
		this.ename = ename;
		this.gender = gender;
		this.role = role;
		this.password = password;
	}

	public User() {
		super();
	}

	@Override
	public String toString() {
		return "User [empno=" + empno + ", ename=" + ename + ", gender=" + gender + ", role=" + role + ", password="
				+ password + "]";
	}
    
    
    
    
    
    
    
}