package com.huawei.cloud.bean;

public class WeChat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.wid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private Integer wid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.addwxid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String addwxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.addwxname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String addwxname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.addtime
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.gender
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.localid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String localid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.localname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private String localname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_wechat.adwid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    private Integer adwid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.wid
     *
     * @return the value of tab_wechat.wid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public Integer getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.wid
     *
     * @param wid the value for tab_wechat.wid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setWid(Integer wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.addwxid
     *
     * @return the value of tab_wechat.addwxid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getAddwxid() {
        return addwxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.addwxid
     *
     * @param addwxid the value for tab_wechat.addwxid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setAddwxid(String addwxid) {
        this.addwxid = addwxid == null ? null : addwxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.addwxname
     *
     * @return the value of tab_wechat.addwxname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getAddwxname() {
        return addwxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.addwxname
     *
     * @param addwxname the value for tab_wechat.addwxname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setAddwxname(String addwxname) {
        this.addwxname = addwxname == null ? null : addwxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.addtime
     *
     * @return the value of tab_wechat.addtime
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.addtime
     *
     * @param addtime the value for tab_wechat.addtime
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setAddtime(String addtime) {
        this.addtime = addtime == null ? null : addtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.gender
     *
     * @return the value of tab_wechat.gender
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.gender
     *
     * @param gender the value for tab_wechat.gender
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.localid
     *
     * @return the value of tab_wechat.localid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getLocalid() {
        return localid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.localid
     *
     * @param localid the value for tab_wechat.localid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setLocalid(String localid) {
        this.localid = localid == null ? null : localid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.localname
     *
     * @return the value of tab_wechat.localname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.localname
     *
     * @param localname the value for tab_wechat.localname
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setLocalname(String localname) {
        this.localname = localname == null ? null : localname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_wechat.adwid
     *
     * @return the value of tab_wechat.adwid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public Integer getAdwid() {
        return adwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_wechat.adwid
     *
     * @param adwid the value for tab_wechat.adwid
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setAdwid(Integer adwid) {
        this.adwid = adwid;
    }
}