package com.huawei.cloud.bean;

import java.util.ArrayList;
import java.util.List;

public class WeChatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public WeChatExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWidIsNull() {
            addCriterion("wid is null");
            return (Criteria) this;
        }

        public Criteria andWidIsNotNull() {
            addCriterion("wid is not null");
            return (Criteria) this;
        }

        public Criteria andWidEqualTo(Integer value) {
            addCriterion("wid =", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotEqualTo(Integer value) {
            addCriterion("wid <>", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThan(Integer value) {
            addCriterion("wid >", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wid >=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThan(Integer value) {
            addCriterion("wid <", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidLessThanOrEqualTo(Integer value) {
            addCriterion("wid <=", value, "wid");
            return (Criteria) this;
        }

        public Criteria andWidIn(List<Integer> values) {
            addCriterion("wid in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotIn(List<Integer> values) {
            addCriterion("wid not in", values, "wid");
            return (Criteria) this;
        }

        public Criteria andWidBetween(Integer value1, Integer value2) {
            addCriterion("wid between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andWidNotBetween(Integer value1, Integer value2) {
            addCriterion("wid not between", value1, value2, "wid");
            return (Criteria) this;
        }

        public Criteria andAddwxidIsNull() {
            addCriterion("addwxid is null");
            return (Criteria) this;
        }

        public Criteria andAddwxidIsNotNull() {
            addCriterion("addwxid is not null");
            return (Criteria) this;
        }

        public Criteria andAddwxidEqualTo(String value) {
            addCriterion("addwxid =", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidNotEqualTo(String value) {
            addCriterion("addwxid <>", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidGreaterThan(String value) {
            addCriterion("addwxid >", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidGreaterThanOrEqualTo(String value) {
            addCriterion("addwxid >=", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidLessThan(String value) {
            addCriterion("addwxid <", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidLessThanOrEqualTo(String value) {
            addCriterion("addwxid <=", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidLike(String value) {
            addCriterion("addwxid like", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidNotLike(String value) {
            addCriterion("addwxid not like", value, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidIn(List<String> values) {
            addCriterion("addwxid in", values, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidNotIn(List<String> values) {
            addCriterion("addwxid not in", values, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidBetween(String value1, String value2) {
            addCriterion("addwxid between", value1, value2, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxidNotBetween(String value1, String value2) {
            addCriterion("addwxid not between", value1, value2, "addwxid");
            return (Criteria) this;
        }

        public Criteria andAddwxnameIsNull() {
            addCriterion("addwxname is null");
            return (Criteria) this;
        }

        public Criteria andAddwxnameIsNotNull() {
            addCriterion("addwxname is not null");
            return (Criteria) this;
        }

        public Criteria andAddwxnameEqualTo(String value) {
            addCriterion("addwxname =", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameNotEqualTo(String value) {
            addCriterion("addwxname <>", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameGreaterThan(String value) {
            addCriterion("addwxname >", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameGreaterThanOrEqualTo(String value) {
            addCriterion("addwxname >=", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameLessThan(String value) {
            addCriterion("addwxname <", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameLessThanOrEqualTo(String value) {
            addCriterion("addwxname <=", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameLike(String value) {
            addCriterion("addwxname like", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameNotLike(String value) {
            addCriterion("addwxname not like", value, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameIn(List<String> values) {
            addCriterion("addwxname in", values, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameNotIn(List<String> values) {
            addCriterion("addwxname not in", values, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameBetween(String value1, String value2) {
            addCriterion("addwxname between", value1, value2, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddwxnameNotBetween(String value1, String value2) {
            addCriterion("addwxname not between", value1, value2, "addwxname");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return (Criteria) this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return (Criteria) this;
        }

        public Criteria andAddtimeEqualTo(String value) {
            addCriterion("addtime =", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotEqualTo(String value) {
            addCriterion("addtime <>", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThan(String value) {
            addCriterion("addtime >", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(String value) {
            addCriterion("addtime >=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThan(String value) {
            addCriterion("addtime <", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(String value) {
            addCriterion("addtime <=", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeLike(String value) {
            addCriterion("addtime like", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotLike(String value) {
            addCriterion("addtime not like", value, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeIn(List<String> values) {
            addCriterion("addtime in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotIn(List<String> values) {
            addCriterion("addtime not in", values, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeBetween(String value1, String value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andAddtimeNotBetween(String value1, String value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andLocalidIsNull() {
            addCriterion("localid is null");
            return (Criteria) this;
        }

        public Criteria andLocalidIsNotNull() {
            addCriterion("localid is not null");
            return (Criteria) this;
        }

        public Criteria andLocalidEqualTo(String value) {
            addCriterion("localid =", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidNotEqualTo(String value) {
            addCriterion("localid <>", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidGreaterThan(String value) {
            addCriterion("localid >", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidGreaterThanOrEqualTo(String value) {
            addCriterion("localid >=", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidLessThan(String value) {
            addCriterion("localid <", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidLessThanOrEqualTo(String value) {
            addCriterion("localid <=", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidLike(String value) {
            addCriterion("localid like", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidNotLike(String value) {
            addCriterion("localid not like", value, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidIn(List<String> values) {
            addCriterion("localid in", values, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidNotIn(List<String> values) {
            addCriterion("localid not in", values, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidBetween(String value1, String value2) {
            addCriterion("localid between", value1, value2, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalidNotBetween(String value1, String value2) {
            addCriterion("localid not between", value1, value2, "localid");
            return (Criteria) this;
        }

        public Criteria andLocalnameIsNull() {
            addCriterion("localname is null");
            return (Criteria) this;
        }

        public Criteria andLocalnameIsNotNull() {
            addCriterion("localname is not null");
            return (Criteria) this;
        }

        public Criteria andLocalnameEqualTo(String value) {
            addCriterion("localname =", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameNotEqualTo(String value) {
            addCriterion("localname <>", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameGreaterThan(String value) {
            addCriterion("localname >", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameGreaterThanOrEqualTo(String value) {
            addCriterion("localname >=", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameLessThan(String value) {
            addCriterion("localname <", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameLessThanOrEqualTo(String value) {
            addCriterion("localname <=", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameLike(String value) {
            addCriterion("localname like", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameNotLike(String value) {
            addCriterion("localname not like", value, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameIn(List<String> values) {
            addCriterion("localname in", values, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameNotIn(List<String> values) {
            addCriterion("localname not in", values, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameBetween(String value1, String value2) {
            addCriterion("localname between", value1, value2, "localname");
            return (Criteria) this;
        }

        public Criteria andLocalnameNotBetween(String value1, String value2) {
            addCriterion("localname not between", value1, value2, "localname");
            return (Criteria) this;
        }

        public Criteria andAdwidIsNull() {
            addCriterion("adwid is null");
            return (Criteria) this;
        }

        public Criteria andAdwidIsNotNull() {
            addCriterion("adwid is not null");
            return (Criteria) this;
        }

        public Criteria andAdwidEqualTo(Integer value) {
            addCriterion("adwid =", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidNotEqualTo(Integer value) {
            addCriterion("adwid <>", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidGreaterThan(Integer value) {
            addCriterion("adwid >", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adwid >=", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidLessThan(Integer value) {
            addCriterion("adwid <", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidLessThanOrEqualTo(Integer value) {
            addCriterion("adwid <=", value, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidIn(List<Integer> values) {
            addCriterion("adwid in", values, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidNotIn(List<Integer> values) {
            addCriterion("adwid not in", values, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidBetween(Integer value1, Integer value2) {
            addCriterion("adwid between", value1, value2, "adwid");
            return (Criteria) this;
        }

        public Criteria andAdwidNotBetween(Integer value1, Integer value2) {
            addCriterion("adwid not between", value1, value2, "adwid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_wechat
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 04 17:25:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tab_wechat
     *
     * @mbg.generated Tue Jun 04 17:25:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}